### ISSUE TITLE
rememberToken

### ISSUE THREAD

**Issue by albsierra** [PruebaED/amigo-animales#1]
https://github.com/PruebaED/amigo-animales/blob/9351f677972ddd0a2681ac8e9d7bb1c131dc25ea/database/migrations/2021_04_21_192753_create_users_table.php#L22

No elimines el atributo rememberToken, ya que te impediría mantener la sesion del usuario abierta, en el caso de que quisieras derle la opción de no cerrar la sesión.

**Comment by PruebaED** [comment]
rememberToken issue solved: https://github.com/PruebaED/amigo-animales/commit/310582c183a6ffbfe22a4ceeae772a0a8ac7bb71
