### ISSUE TITLE
Seeders

### ISSUE THREAD

**Issue by albsierra** [PruebaED/amigo-animales#2]
https://github.com/PruebaED/amigo-animales/blob/aa786626f2b4bc90cdb47fc14bca065086a46483/amigo-animales.sql#L2

Traslada estos insert a un fichero seeder en el directorio database/seeders.
Además, los animales los podrías generar con un [Factoy](https://laravel.com/docs/8.x/database-testing#defining-model-factories) utilizando la librería faker.

**Comment by PruebaED** [comment]
Al final he optado por usar la librería faker únicamente para la generación de los 5 primeros usuarios para tenerlos disponibles para las posibles pruebas.

seeders issue solved: https://github.com/PruebaED/amigo-animales/commit/37c67ffb4231c7215a8770ad82280889d0cad22f
