### ISSUE TITLE
Diseño de la base de datos

### ISSUE THREAD

**Issue by albsierra** [PruebaED/amigo-animales#3]
https://github.com/PruebaED/amigo-animales/blob/df26ff3204b118e3246d494281a0d8ad1cea8e07/Relaciones.drawio#L1

Todavía no has generado una tabla de adopciones y/o acogimientos. Ten en cuenta que si un animal primero se acoge y luego se adopta, esos cambios conviene registrarlos.

Recuerda también que convendría establecer algún sistema de mensajería entre los propietarios de los animales desaparecidos y los que los encuentran.

**Comment by PruebaED** [comment]
Tengo que pensar la forma en la que voy a registrar las adopciones, los acogimientos, étc

Respecto a lo de los animales desaparecidos, la idea sería mostrar el teléfono del usuario que ha perdido el animal y efectivamente, darle la opción a cualquier persona para que pueda hacer un reporte rápido (indicando dónde lo ha visto, a qué hora y una forma de contactar con el que hace este reporte) el cual será enviado al correo del dueño/a del animal desaparecido.

**Comment by PruebaED** [comment]
Diseño de la base de datos issue solved: https://github.com/PruebaED/amigo-animales/commit/6f7cda015a30ea69485c4f832c3682a067085e4c

*Queda pendiente establecer el sistema de mensajería entre propietarios de animales desaparecidos y los que los encuentran
