### ISSUE TITLE
Faker de teléfonos

### ISSUE THREAD

**Issue by albsierra** [PruebaED/amigo-animales#4]
https://github.com/PruebaED/amigo-animales/blob/f1d3359c00ee5a084f4fcaecc7a1a21048c790be/database/factories/UserFactory.php#L30

Hay un ["faker" para los teléfonos](https://github.com/fzaninotto/Faker#fakerprovideres_esphonenumber).

Aunque quizás tengas que seleccionar el idioma español al inicializar el faker:
`$faker = Faker\Factory::create('fr_FR');`

**Comment by PruebaED** [comment]
Faker de teléfonos issue solved: https://github.com/PruebaED/amigo-animales/commit/a3c1d48b831a8cb60b31a9eff05b5eb78066afba
