### ISSUE TITLE
destroyAccount

### ISSUE THREAD

**Issue by albsierra** [PruebaED/amigo-animales#5]
https://github.com/PruebaED/amigo-animales/blob/f93a25eda49fcd3ee536838ca6f1276de5bb3b37/resources/views/settings/account.blade.php#L50

Borrar un recurso (como una cuenta) debe ser una acción `DELETE` y no `PUT`

**Comment by PruebaED** [comment]
destroyAccount issue solved: https://github.com/PruebaED/amigo-animales/commit/cf4aeea29d0b5fb6ef6eed2fef0db3ac54ea93a9
