### ISSUE TITLE
Motivo de la consulta TextArea

### ISSUE THREAD

**Issue by albsierra** [PruebaED/amigo-animales#8]
https://github.com/PruebaED/amigo-animales/blob/eb1098cc5d8e67c68b9114cb14b3cf20b9b1381a/routes/web.php#L28

El motivo de la consulta, en el formulario de contacto, debería ser un textarea.

**Comment by PruebaED** [comment]
Motivo de la consulta TextArea issue solved: https://github.com/PruebaED/amigo-animales/commit/8d0b318807df62a7cfaa97a3aa924cb019bbc6a8
