### ISSUE TITLE
Anunciar desaparición.

### ISSUE THREAD

**Issue by albsierra** [PruebaED/amigo-animales#9]
https://github.com/PruebaED/amigo-animales/blob/eb1098cc5d8e67c68b9114cb14b3cf20b9b1381a/routes/web.php#L42

Me falta una opción para anunciar la desaparición de un animal propio. Quizás simplemente es que yo no la he encontrado.

**Comment by PruebaED** [comment]
Anunciar desaparición issue solved: https://github.com/PruebaED/amigo-animales/commit/99901c459c63963c98987dc96648cd581ca4a504
